/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apotek;

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reinandy Fediyanto
 */
public class transaksi extends javax.swing.JFrame {

    /**
     * Creates new form transaksi
     */
    public Statement st;
    public ResultSet rs;
    public String a;
    public String rba;
    public DefaultTableModel tabmodel;
    Connection cn = koneksi.koneksi.getKoneksi();
    
    public transaksi() {
        initComponents();
        tampilData();
        cb_box.setEnabled(false);
        rb.setEnabled(false);
        rb2.setEnabled(false);
        rb3.setEnabled(false);
        harga.setEnabled(false);
        total.setEnabled(false);
        kembali.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nm_tsk = new javax.swing.JComboBox<>();
        cb_box = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kembali = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jmb = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        rb = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("BELI OBAT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nama Obat");

        nm_tsk.setBackground(new java.awt.Color(255, 204, 102));
        nm_tsk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--" }));
        nm_tsk.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nm_tskItemStateChanged(evt);
            }
        });

        cb_box.setBackground(new java.awt.Color(255, 204, 102));
        cb_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--", "Dewasa", "Anak-anak" }));
        cb_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_boxItemStateChanged(evt);
            }
        });
        cb_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_boxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Obat Untuk");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Jenis Obat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Jumlah Beli");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Total");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Bayar");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Kembali");

        kembali.setBackground(new java.awt.Color(255, 204, 102));

        bayar.setBackground(new java.awt.Color(255, 204, 102));
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
        });

        total.setBackground(new java.awt.Color(255, 204, 102));

        jmb.setBackground(new java.awt.Color(255, 204, 102));
        jmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmbKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jmbKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jmbKeyTyped(evt);
            }
        });

        harga.setBackground(new java.awt.Color(255, 204, 102));
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        rb.setBackground(new java.awt.Color(255, 204, 102));
        buttonGroup1.add(rb);
        rb.setText("kapsul");
        rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActionPerformed(evt);
            }
        });

        rb2.setBackground(new java.awt.Color(255, 204, 102));
        buttonGroup1.add(rb2);
        rb2.setText("bubuk");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        rb3.setBackground(new java.awt.Color(255, 204, 102));
        buttonGroup1.add(rb3);
        rb3.setText("cair");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setText("Beli");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(nm_tsk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rb2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rb3))
                                .addComponent(cb_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(kembali, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jmb, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(harga, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bayar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nm_tsk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rb)
                    .addComponent(rb2)
                    .addComponent(rb3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_boxActionPerformed

    }//GEN-LAST:event_cb_boxActionPerformed

    private void rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActionPerformed
//        rba = rb.getText();
    }//GEN-LAST:event_rbActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
//        rba = rb2.getText();
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
//        rba = rb3.getText();
    }//GEN-LAST:event_rb3ActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void cb_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_boxItemStateChanged

    }//GEN-LAST:event_cb_boxItemStateChanged

    private void nm_tskItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nm_tskItemStateChanged
        tampilData2();
    }//GEN-LAST:event_nm_tskItemStateChanged

    private void jmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmbKeyReleased
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(null,"Harus diisi angka");
        jmb.setText("");
        }else{
        int a = Integer.parseInt(harga.getText());
        int b = Integer.parseInt(jmb.getText());
        String c = Integer.toString(a*b);
        total.setText(c);
        }
    }//GEN-LAST:event_jmbKeyReleased

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(null,"Harus diisi angka");
        bayar.setText("");
        }else{
        int a = Integer.parseInt(bayar.getText());
        int b = Integer.parseInt(total.getText());
        String c = Integer.toString(a-b);
        kembali.setText(c);
        }
    }//GEN-LAST:event_bayarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int z = Integer.parseInt(kembali.getText());
        if(z<0){
            JOptionPane.showMessageDialog(null,"Uang anda kurang");
        }else{
            JOptionPane.showMessageDialog(null,"Terima kasih sudah membeli di apotek kami :) :)");
            try{
                if(rb.isSelected()){
                rba = rb.getText();
                }else if(rb2.isSelected()){
                rba = rb2.getText();
                }else if(rb3.isSelected()){
                rba = rb3.getText();
                }else{
                JOptionPane.showMessageDialog(null,"Terjadi kesalahan sintak");    
                }
            st = cn.createStatement();
            st.executeUpdate("insert into tb_transaksi set nama_obat='"+nm_tsk.getSelectedItem()+"', obat_untuk='"+cb_box.getSelectedItem()+"',jenis='"+rba+"', harga='"+harga.getText()+"', jumlah_beli='"+jmb.getText()+"', total='"+total.getText()+"', bayar='"+bayar.getText()+"',kembali='"+kembali.getText()+"';");
            JOptionPane.showMessageDialog(null,"Tersimpan");
            try{
            Desktop.getDesktop().browse(new URL("http://localhost:81/report_java/struk.php").toURI());
        }catch(Exception e){
            e.printStackTrace();
        }
            reset();
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmbKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jmbKeyTyped

    private void jmbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmbKeyPressed
        
    }//GEN-LAST:event_jmbKeyPressed

    /**
     * @param args the command line arguments
     */
    
    public void tampilData() {
        try{
            st = cn.createStatement();
            rs = st.executeQuery("select * from tb_obat;");
            while (rs.next()){
                nm_tsk.addItem(rs.getString("nama_obat"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void tampilData2() {
        try{
            st = cn.createStatement();
            rs = st.executeQuery("select * from tb_obat where nama_obat='"+nm_tsk.getSelectedItem()+"'");
            System.out.println(nm_tsk.getSelectedItem());
            System.out.println("jalan");
            while(rs.next()){
                System.out.println(rs.getString("obat_untuk"));
                System.out.println(rs.getString("stok"));
                cb_box.setSelectedItem(rs.getString("obat_untuk"));
                harga.setText(rs.getString("stok"));
                a = rs.getString("jenis");
                if(a.equals("kapsul")){
                    rb.setSelected(true);
                }else if(a.equals("bubuk")){
                    rb2.setSelected(true);
                }else if(a.equals("cair")){
                    rb3.setSelected(true);
                }else{
                    System.out.println("gagal");
                }
            }
//            while (rs.next()){
//                cbx1.addItem(rs.getString("nama_obat"));
//            }
//            rs.last();
//            int jumlahdata = rs.getRow();
//            rs.first();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_box;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jmb;
    private javax.swing.JTextField kembali;
    private javax.swing.JComboBox<String> nm_tsk;
    private javax.swing.JRadioButton rb;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
    public void reset(){
        nm_tsk.setSelectedItem("--pilih--");
        cb_box.setSelectedItem("--pilih--");
        buttonGroup1.clearSelection();
        harga.setText("");
        jmb.setText("");
        total.setText("");
        bayar.setText("");
        kembali.setText("");
    }
}
